djangostripe/djangostripe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls", namespace="items")),
]

djangostripe/products/urls.py
from django.urls import path
from . import views
from .views import (
    ItemDetailView,
    ItemListView,
)

app_name = "items"

urlpatterns = [
    path("", ItemListView.as_view(), name="item-list"),
    path("item/<int:pk>/", views.item_detail, name="item-detail"),
    path("buy/<int:pk>/", views.create_checkout_session, name="api")
]

djangostripe/products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Item(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(_("Description"), blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=10)

    def __str__(self):
        return f"{self.name} {self.price}"

djangostripe/products/views.py
from django.shortcuts import render, redirect
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.views.generic import DetailView, ListView
from .models import Item
import stripe

stripe.api_key = 'sk_test_51Oo5YsHONtmivArNXAcmSqn1UtrzsWj8eI1Q6vWNtLLOymNlK68WQhHlZVKA9FNxvdvnwCMYvODWZCBVABRZbcxV00rAcg20BS'

@api_view(['GET'])
def create_checkout_session(request, pk):
    if request.method == "GET":
        item = Item.objects.all()
        item = str(item[pk - 1])
        price = item.split()
        price = price[len(price) - 1].replace('.', '')
        session = stripe.checkout.Session.create(
            line_items=[{
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': item[:-len(price)-1],
                    },
                    'unit_amount': int(price),
                },
                'quantity': 1,
            }],
            mode='payment',
            success_url='http://localhost:8000/success',
            cancel_url='http://localhost:8000/cancel',
        )
        data = {'sessionId': session.id}
        return Response(data)

class ItemListView(ListView):
    model = Item
    context_object_name = "items"
    template_name = "products/item_list.html"


class ItemDetailView(DetailView):
    model = Item
    context_object_name = "items"
    template_name = "products/item_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ItemDetailView, self).get_context_data()
        Price = str(self.get_object()).split(' ')[1]
        context["prices"] = Price
        return context


@api_view(["GET"])
def item_detail(request, pk):
    if request.method == "GET":
        items = Item.objects.all()
        items = [items[pk-1]]
        context = {'items': items}
        template_name = "products/item_detail.html"

        return render(request, template_name, context=context)

djangostripe/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

  <script src="https://js.stripe.com/v3/" async></script>

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <!--Font awesome icons -->
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
      integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
      crossorigin="anonymous"
    />

{#    <link#}
{#      rel=""#}
{#      href="https://js.stripe.com/v3/"#}
{#      integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"#}
{#      crossorigin="anonymous"#}
{#    />#}

    {% block script %}{% endblock %}

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <div class="container p-3 my-3">
      <div class="row">
        <div class="col-md-12">
          <!--Any flash messages pop up in any page because this is the base template-->
          {% if messages %}
          <div class="alert alert-dismissible" role="alert">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <button
              type="button"
              class="close"
              data-dismiss="alert"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %} {% block content %}{% endblock %}
        </div>
      </div>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

djangostripe/templates/products/item_detail.html
{% extends "base.html" %}
{% comment %} templates/products/item_detail.html {% endcomment %}

{% block title %} Buy Item {% endblock title %}
{% block content %}
{% for item in items %}
<div class="card-deck">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">{{ item.name }}</h5>
      <p class="card-text">{{ item.description }}</p>
      <div class="card-text">
        <h5 class="card-text">${{ item.price }}</h5>
          <form>
            <input type="button" value="Buy Now" onclick="getSessionId({{ item.id }});">
              <script>
    function getSessionId(itemId) {
        const stripe = Stripe('pk_test_51Oo5YsHONtmivArNZKrU0i4bkl7qHaCdUoozBjlQvdhlpWS2mlbJScyTPk5MZ8AWtFN2VeNHU6mq6YfS9s269Yzd00Mfai1rMU');

        fetchData(itemId)
                .then((response) => {
                    return response.json();
                })
                .then((session) => {
                    stripe.redirectToCheckout({ sessionId: session.sessionId })
                })
                .catch((err) => {
                    alert(err);
                });
            return null;
        }

        async function fetchData(itemId) {
            const url = `/buy/${itemId}`;
            return await fetch(url, { method: "GET" })
    }
</script>
          </form>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

djangostripe/templates/products/item_list.html
{% extends "base.html" %}
{% comment %} templates/products/item_list.html {% endcomment %}

{% block title %} Items {% endblock title%} {% block content %} {% for item in items %}
<div class="card" style="width: 18rem">
  <div class="card-body">
    <h5 class="card-title">{{item.name}}</h5>
    <p class="card-text">{{item.description}}</p>
    <a
      href="{% url 'items:item-detail' item.id %}"
      class="btn btn-primary"
      >View Detail</a
    >
  </div>
</div>
{% endfor %} {% endblock content %}